# Generated by Django 6.0.3 on 2026-04-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mosquitos', '0003_intervention_intervention_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='is_treatable',
            field=models.BooleanField(default=True),
        ),
    ]
